# Generated by Django 5.2.1 on 2025-06-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=255)),
                ('foodimg', models.ImageField(upload_to='')),
                ('foodinfo', models.TextField(default='No information available')),
                ('foodprice', models.IntegerField(blank=True, null=True)),
                ('videoSrc', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('videos', 'Videos'), ('books', 'Books'), ('burger', 'Burger'), ('pizza', 'Pizza'), ('biryani', 'Biryani'), ('noodles', 'Noodles'), ('cake', 'Cake'), ('momos', 'Momos'), ('ice cream', 'Ice cream'), ('sweet', 'Sweet'), ('northfood', 'Northfood'), ('southfood', 'Southfood'), ('topfood', 'Topfood')], max_length=255)),
            ],
        ),
    ]
