# Generated by Django 5.2.1 on 2025-06-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeproject', '0002_alter_recipes_videosrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('repassword', models.CharField(max_length=100, null=True)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cart', models.CharField(default='[]', max_length=255)),
                ('likes', models.CharField(default='[]', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='recipes',
            name='category',
            field=models.CharField(choices=[('videos', 'Videos'), ('books', 'Books'), ('burger', 'Burger'), ('pizza', 'Pizza'), ('noodles', 'Noodles'), ('biryani', 'Biryani'), ('ice cream', 'Ice cream'), ('sweet', 'Sweet'), ('northfood', 'Northfood'), ('southfood', 'Southfood'), ('topfood', 'Topfood')], max_length=255),
        ),
    ]
