# Generated by Django 5.2.1 on 2025-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeproject', '0003_users_alter_recipes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='likesr',
            field=models.CharField(default='[]', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='likesv',
            field=models.CharField(default='[]', max_length=255),
        ),
    ]
