from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage),
    path('recipe',views.recipe),
    path('recipeshow/<int:Id>',views.recipeshow),
    path('video',views.video),
    path('videoshow/<int:Id>',views.videoshow),
    path('books',views.books),
    path('orderfood',views.orderfood),    
    path('ordershow/<int:Id>',views.ordershow),
    path('burger',views.burger),
    path('pizza',views.pizza),
    path('chinese', views.noodles),
    path('biryani', views.biryani),
    path('ice', views.icecream), 
    path('sweet', views.sweet),
    path('northfood', views.northfood),
    path('southfood', views.southfood),
    path('signup',views.signup),
    path('login',views.login),
    path('profile',views.profile),
    path('addlikeitem/<int:Id>/', views.addlikeitem, name='addlikeitem'),
    path('like',views.like),
    path('addlikeitemv/<int:Id>/', views.addlikeitemv, name='addlikeitem'),
    path('videolike',views.videolike),
    path('removelikeitem/<int:Id>/', views.removelikeitem, name=' removelikeitem'), 
    path('addbuyitem/<int:Id>/', views.addbuyitem, name='addbuyitem'),
    path('carts/', views.carts, name='carts'),
    path('addlikeitemrs/<int:Id>/', views.addlikeitemrs),
    path('recipelike',views.recipelike),
    path('searchfood/<str:item>/',views.searchfood),
    path('about',views.about),
    path('terms',views.terms),
    path('privacy',views.privacy),
    path('support',views.support),
    path('removevideoitem/<int:Id>/', views.removevideoitem), 
    path('removerecipeitem/<int:Id>/', views.removerecipeitem), 
    path('removebuyitem/<int:Id>/', views.removebuyitem), 
    path('results', views.recipe_results, name='recipe_result'),
]